CREATE TABLE public.productlenders (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	productName varchar(255) NOT NULL,
	rrp numeric(16,4) NOT NULL,
	rentPrice numeric(16,4) NULL,
	brand varchar(255) NOT NULL,
	ocassion varchar(255) NOT NULL,
	category varchar(255) NOT NULL,
	lenderId int8 NOT NULL,
	addedAt timestamp,
	CONSTRAINT fk_productlenderuser
          FOREIGN KEY(lenderId)
    	  REFERENCES users(id),
	CONSTRAINT productlenderpkey PRIMARY KEY (id)
);

CREATE TABLE public.productimageurl (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	productId int8 NOT NULL,
	imageUrl varchar(2000) NOT NULL,
	isThumbnail bool NOT NULL,
	CONSTRAINT fk_productlenderId
          FOREIGN KEY(productId)
    	  REFERENCES productlenders(id),
	CONSTRAINT productimagepkey PRIMARY KEY (id)
);
