name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t vinit3101/fashionrent .
      - name: Publish image to docker hub
        run: docker push vinit3101/fashionrent:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: "Free up disk space"
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Pull Image from docker hub
        run: sudo docker pull vinit3101/fashionrent:latest
      - name: Delete old container
        run: sudo docker rm -f fashionrent-container
      - name: Run docker container
        run: sudo docker run -d -p 8383:8383 --name fashionrent-container vinit3101/fashionrent
